### ISSUE TITLE
Image Storage

### ISSUE THREAD

**Issue by jiahao-c** [jhcccc/Code-Snippets#1]

**Comment by jiahao-c** [comment]
![img](https://user-images.githubusercontent.com/8275280/77021766-0fbb5900-695e-11ea-9c8d-a15aa78547a1.jpg)

**Comment by jiahao-c** [comment]
![image](https://user-images.githubusercontent.com/8275280/77283747-58d71a00-6c8a-11ea-8bb8-c5debdd52063.png)

**Comment by jiahao-c** [comment]
![game-background](https://user-images.githubusercontent.com/8275280/81189380-12930b80-8fe9-11ea-8ae1-18b9060788e8.jpg)

**Comment by jhcccc** [comment]
![drag](https://user-images.githubusercontent.com/8275280/81415286-d1326580-917a-11ea-8304-6d339104ed1b.png)

**Comment by jiahao-c** [comment]
![drag](https://user-images.githubusercontent.com/8275280/81415609-3f772800-917b-11ea-8c2f-f9fc7483e2b3.png)

**Comment by jiahao-c** [comment]
![correct](https://user-images.githubusercontent.com/8275280/81571666-d4289280-93d4-11ea-95f9-ed275769938a.png)
![wrong](https://user-images.githubusercontent.com/8275280/81571670-d5f25600-93d4-11ea-82ed-cb19a415bd61.png)

**Comment by jiahao-c** [comment]
![start](https://user-images.githubusercontent.com/8275280/82016449-aaf95200-96b3-11ea-9fb8-9043b4d2bbe4.png)
![you-win-png-4](https://user-images.githubusercontent.com/8275280/82016484-bf3d4f00-96b3-11ea-9c09-493e96e54853.png)
![unnamed](https://user-images.githubusercontent.com/8275280/82016612-fb70af80-96b3-11ea-9cc2-61701ac17859.png)

**Comment by jiahao-c** [comment]
![GameCover](https://user-images.githubusercontent.com/8275280/82331593-eaf36880-9a16-11ea-94f4-b9f2baeb5044.png)
